blog/urls.py
from django.urls import path

from .views import render_posts,post_detail
app_name = 'blog'
urlpatterns = [
    path('', render_posts, name='posts'),
    path("/<int:post_id>", post_detail, name='post_detail')
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include, include
from django.conf.urls.static import static
import blog
from django_portfolio.settings import STATIC_URL
from django.conf import settings

# import views of frontend 
from portfolio import views
# add and define urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/models.py
import datetime
from django.db import models
from django.db.models.base import Model
import datetime

# Create your models here.
class Post(models.Model):
    # Import type vars; second form
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images/")
    date = models.DateField(datetime.date.today)



# Import type vars; first form
# from django.db.models.fields import CharField, URLField
# from django.db.models.fields.files import ImageField
# class Post(models.Model):
#     title = CharField(max_length=100)
#     description = CharField(max_length=250)
#     image = ImageField(upload_to="portfolio/images/")
#     date = URLField(blank=True)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

# Model es una clase que va a heredar models.
# crearemos las variables, los tipos deben ser importados
class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images/")
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
# Create your views here.

def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {
        'posts': posts
    })

def post_detail(request, post_id):
    post = get_object_or_404(Post,pk=post_id)
    return render(request, 'post_detail.html', {"post": post})

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.

def home(request):
    projects = Project.objects.all()

    return render(request, 'home.html',
    {'projects': projects}
    )

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}
    <div class="text-center">
        <h2>{{post.title}}</h2> 
        <small class="my-2 text-muted"> {{post.date|date:'F jS Y'}}</small>
        <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
        <div class="my-4">
            <p>{{post.description|safe}}</p>
        </div>
    </div>
{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="my-3">POSTS</h1>
    {% for post in posts %}
        <div class="p-3">
            <div class="card card-body bg-black">
                <div class="row">
                    <div class="col-md-3">
                        <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
                    </div>
                    <div class="col-md-9">
                        <h2>{{post.title}}</h2> <small> {{post.date|date:'M d Y'}}</small>
                        <p>{{post.description|striptags|truncatechars:120}}</p>
                        <a class="btn btn-primary btn-sm" href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}
    {% block content %}
        {% load static %}
        <header class="row bg-black my-3 py-3">
            <div class="col-md-4">
                <img style="border-radius: 50%;" src="{% static 'portfolio/profile.jpg' %}" alt="" width="300px">
            </div>
            <div class="col-md-8 my-auto">
                <h1>Hi!, I'm <strong>Natanael Corona</strong></h1>
                <h4>And I'm Python FullStack Web Developer</h4>
                <p class="font-monospace text-wrap lh-sm">I am a university student, but my scheme of learning and development of skills, is based on a personal interest and
                autonomy to learn new things, but increasingly complex, in order to open the way to new opportunities that allow me to
                exploit my full potential, creating solutions to problems making use of my greatest passion, programming.
                </p>
                <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'portfolio/JNCC_CV.pdf' %}" target="_blank">Download CV</a>
            </div>
        </header>

        <div class="row my-4 text-center">
            <h3>Projects</h3>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, eveniet!</p>
            {% for project in projects %}
                <div class="col-md-4 p-4">
                    <div class="card bg-black card-project">
                        <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top">
                        <div class="card-body">
                            <h2>{{project.title}}</h2>
                            <p>{{project.description}}</p>
                            {% if project.url %}
                                <a href="{{project.url}}" class="btn btn-primary btn-sm" target="_blank">{{project.url}}</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endblock %}

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio projects</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">

    {% include 'partials/navbar.html' %}

   <div class="container">
    {% block content %}
    {% endblock %}
   </div>

</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold font-monospace" href="/">NathScrapps</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item mx-2">
            <a class="nav-link" aria-current="page" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/JNCC_CV.pdf' %}" target="_blank">Download CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>